// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: proto/keywords.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// KeywordsClient is the client API for Keywords service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeywordsClient interface {
	FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllRes, error)
}

type keywordsClient struct {
	cc grpc.ClientConnInterface
}

func NewKeywordsClient(cc grpc.ClientConnInterface) KeywordsClient {
	return &keywordsClient{cc}
}

func (c *keywordsClient) FindAll(ctx context.Context, in *FindAllReq, opts ...grpc.CallOption) (*FindAllRes, error) {
	out := new(FindAllRes)
	err := c.cc.Invoke(ctx, "/leoh_package.Keywords/FindAll", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeywordsServer is the server API for Keywords service.
// All implementations must embed UnimplementedKeywordsServer
// for forward compatibility
type KeywordsServer interface {
	FindAll(context.Context, *FindAllReq) (*FindAllRes, error)
	mustEmbedUnimplementedKeywordsServer()
}

// UnimplementedKeywordsServer must be embedded to have forward compatible implementations.
type UnimplementedKeywordsServer struct {
}

func (UnimplementedKeywordsServer) FindAll(context.Context, *FindAllReq) (*FindAllRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FindAll not implemented")
}
func (UnimplementedKeywordsServer) mustEmbedUnimplementedKeywordsServer() {}

// UnsafeKeywordsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeywordsServer will
// result in compilation errors.
type UnsafeKeywordsServer interface {
	mustEmbedUnimplementedKeywordsServer()
}

func RegisterKeywordsServer(s grpc.ServiceRegistrar, srv KeywordsServer) {
	s.RegisterService(&Keywords_ServiceDesc, srv)
}

func _Keywords_FindAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FindAllReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeywordsServer).FindAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leoh_package.Keywords/FindAll",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeywordsServer).FindAll(ctx, req.(*FindAllReq))
	}
	return interceptor(ctx, in, info, handler)
}

// Keywords_ServiceDesc is the grpc.ServiceDesc for Keywords service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Keywords_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leoh_package.Keywords",
	HandlerType: (*KeywordsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "FindAll",
			Handler:    _Keywords_FindAll_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/keywords.proto",
}
