server:
  host: "0.0.0.0"
  port: 50052
  access_token: "9jey84prEhw5u43780yjr3h7sksSdkFdDngKie8nth0yi29405nr"
mysql:
  # 确保chatgpt-data能访问mysql所在的ip，这里最好是配置公网ip，满足分布式部署
  dsn: "root:123456@tcp(192.168.10.129:3306)/chatGPT?collation=utf8mb4_unicode_ci&charset=utf8mb4"
  maxLifeTime: 3600
  maxOpenConn: 10
  maxIdleConn: 10
log:
  # panic,fatal,error,warn,warning,info,debug,trace
  level: "info"
  log_path: "runtime/app.log"
