// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.22.0
// source: services/chatgpt-service/proto/chatgpt.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatGPTClient is the client API for ChatGPT service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatGPTClient interface {
	ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error)
	ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (ChatGPT_ChatCompletionStreamClient, error)
}

type chatGPTClient struct {
	cc grpc.ClientConnInterface
}

func NewChatGPTClient(cc grpc.ClientConnInterface) ChatGPTClient {
	return &chatGPTClient{cc}
}

func (c *chatGPTClient) ChatCompletion(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (*ChatCompletionResponse, error) {
	out := new(ChatCompletionResponse)
	err := c.cc.Invoke(ctx, "/leoh_package.ChatGPT/ChatCompletion", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatGPTClient) ChatCompletionStream(ctx context.Context, in *ChatCompletionRequest, opts ...grpc.CallOption) (ChatGPT_ChatCompletionStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatGPT_ServiceDesc.Streams[0], "/leoh_package.ChatGPT/ChatCompletionStream", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatGPTChatCompletionStreamClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type ChatGPT_ChatCompletionStreamClient interface {
	Recv() (*ChatCompletionStreamResponse, error)
	grpc.ClientStream
}

type chatGPTChatCompletionStreamClient struct {
	grpc.ClientStream
}

func (x *chatGPTChatCompletionStreamClient) Recv() (*ChatCompletionStreamResponse, error) {
	m := new(ChatCompletionStreamResponse)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatGPTServer is the server API for ChatGPT service.
// All implementations must embed UnimplementedChatGPTServer
// for forward compatibility
type ChatGPTServer interface {
	ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error)
	ChatCompletionStream(*ChatCompletionRequest, ChatGPT_ChatCompletionStreamServer) error
	mustEmbedUnimplementedChatGPTServer()
}

// UnimplementedChatGPTServer must be embedded to have forward compatible implementations.
type UnimplementedChatGPTServer struct {
}

func (UnimplementedChatGPTServer) ChatCompletion(context.Context, *ChatCompletionRequest) (*ChatCompletionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChatCompletion not implemented")
}
func (UnimplementedChatGPTServer) ChatCompletionStream(*ChatCompletionRequest, ChatGPT_ChatCompletionStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method ChatCompletionStream not implemented")
}
func (UnimplementedChatGPTServer) mustEmbedUnimplementedChatGPTServer() {}

// UnsafeChatGPTServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatGPTServer will
// result in compilation errors.
type UnsafeChatGPTServer interface {
	mustEmbedUnimplementedChatGPTServer()
}

func RegisterChatGPTServer(s grpc.ServiceRegistrar, srv ChatGPTServer) {
	s.RegisterService(&ChatGPT_ServiceDesc, srv)
}

func _ChatGPT_ChatCompletion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChatCompletionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatGPTServer).ChatCompletion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/leoh_package.ChatGPT/ChatCompletion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatGPTServer).ChatCompletion(ctx, req.(*ChatCompletionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatGPT_ChatCompletionStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ChatCompletionRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(ChatGPTServer).ChatCompletionStream(m, &chatGPTChatCompletionStreamServer{stream})
}

type ChatGPT_ChatCompletionStreamServer interface {
	Send(*ChatCompletionStreamResponse) error
	grpc.ServerStream
}

type chatGPTChatCompletionStreamServer struct {
	grpc.ServerStream
}

func (x *chatGPTChatCompletionStreamServer) Send(m *ChatCompletionStreamResponse) error {
	return x.ServerStream.SendMsg(m)
}

// ChatGPT_ServiceDesc is the grpc.ServiceDesc for ChatGPT service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatGPT_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "leoh_package.ChatGPT",
	HandlerType: (*ChatGPTServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ChatCompletion",
			Handler:    _ChatGPT_ChatCompletion_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ChatCompletionStream",
			Handler:       _ChatGPT_ChatCompletionStream_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "services/chatgpt-service/proto/chatgpt.proto",
}
